name: myip
version: "1"
license: Unlicense
summary: show external IP address
description: |
  uses DNS protocol and `dig` tool to query external IP from OpenDNS
  
base: core20

apps:
  myip:
    command: myip.sh

parts:
  myip:
    plugin: nil
    stage-packages:
      # install `dig` utility
      - dnsutils
    source: .
    # overriding the build/ step to copy the script for packing
    # https://snapcraft.io/docs/parts-lifecycle#heading--parts-directories
    override-build: |
      cp myip.sh $SNAPCRAFT_PART_INSTALL/
