name: yakshaveinc
version: eternal
license: Unlicense
summary: minimal empty snap that builds
description: |
  empty artifact delivered through the pipeline
  [ GitHub ]->- [ Travis CI ]->- [ Snap Store ]

base: core18

parts:
  yakshaveinc:
    plugin: nil

