name: yakshaveinc
version: eternal
license: Unlicense
summary: minimal snap that builds
description: |
  an artifact that is delivered through the pipeline
  [ GitHub ]->- [ Travis CI ]->- [ Snap Store ]

base: core18

parts:
  yakshaveinc:
    plugin: nil

