on:
  # run if another workflow completes
  workflow_run:
    workflows: [02context.yaml]
    types:
      - completed
  
jobs:
  context-on-success:
    runs-on: ubuntu-latest
    # only run if parent workflow was successful (gating)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump workflow_run context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.workflow_run) }}
        run: echo "$GITHUB_CONTEXT"
